name: Run Selenium Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Максимальное время выполнения

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium
        sudo apt-get update
        sudo apt-get install -y firefox xvfb

    - name: Install GeckoDriver
      run: |
        GECKODRIVER_VERSION='v0.34.0'
        wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/
        geckodriver --version

    - name: Run tests with headless Firefox
      run: |
        xvfb-run -a python -m pytest tests/ -v --junitxml=test-results/junit.xml
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()  # Загружать артефакты даже если тесты упали
      with:
        name: test-results
        path: test-results
    - name: Test with pytest
      run: |
        python -m pytest tests/ -v
